name: recombee_client
description: Recombee API Wrapper.
version: 0.0.2
homepage: https://github.com/indmind/recombee-client

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.3
  crypto: ^3.0.1

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.17.10
